---
- name: append key to addon
  set_fact:
    pillar_k8s_addon: "{{ pillar_k8s_addon | default(pillar['k8s_addon']) | combine({item: {'key': item}}, recursive=True) }}"
  loop: "{{ pillar.k8s_addon.keys() }}"

- name: addon config
  template:
    src: addon/{{ item.0.key }}/{{ item.1 }}.yml.j2
    dest: /tmp/addon_{{ item.0.key }}_{{ item.1 }}.yml
  with_subelements: 
    - "{{ pillar_k8s_addon }}"
    - config_files
    - flags:
      skip_missing: True
  when: inventory_hostname in (pillar.k8s_host.master[0])
