---
- name: append key to app
  set_fact:
    pillar_k8s_app: "{{ pillar_k8s_app | default(pillar['k8s_app']) | combine({item: {'key': item}}, recursive=True) }}"
  loop: "{{ pillar.k8s_app.keys() }}"

- name: create app
  shell: kubectl --kubeconfig={{ pillar.k8s_common.conf_dir }}/admin.conf apply -f /tmp/app_{{ item.0.key }}_{{ item.1 }}.yml
  with_subelements: 
    - "{{ pillar_k8s_app }}"
    - config_files
    - flags:
      skip_missing: True
  when: inventory_hostname in (pillar.k8s_host.master[0])
