---
- name: ensure cfssl bin directory is create
  file:
    path: "{{ pillar.cfssl_common.bin_dir }}"
    state: directory
    mode: 0755

- name: Download statically linked cfssl binary
  get_url:
    url: "{{ pillar.cfssl_common.url }}/{{ item.key }}"
    dest: "{{ pillar.cfssl_common.bin_dir }}/{{ item.value.dest }}"
    checksum: "{{ item.value.checksum }}"
    mode: 0755
  with_dict: "{{ pillar.cfssl_pkgs }}"

- name: ensure k8s bin directory is create
  file:
    path: "{{ pillar.k8s_pkgs_common.bin_dir }}"
    state: directory
    mode: 0755

- name: Download statically linked k8s binary
  get_url:
    url: "{{ pillar.k8s_pkgs_common.url }}/{{ item.key }}"
    dest: "{{ pillar.k8s_pkgs_common.bin_dir }}/{{ item.value.dest }}"
    checksum: "{{ item.value.checksum }}"
    mode: 0755
  with_dict: "{{ pillar.k8s_pkgs }}"

- name: ensure cni plugin directory is create
  file:
    path: "{{ pillar.cni_common.bin_dir }}"
    state: directory
    mode: 0755

- name: Download and unarchive cni plugin
  unarchive:
    src: "{{ pillar.cni_common.url }}"
    dest: "{{ pillar.cni_common.bin_dir }}"
    remote_src: yes
