---
- name: append key to extra_addon
  set_fact:
    pillar_k8s_extra_addon: "{{ pillar_k8s_extra_addon | default(pillar['k8s_extra_addon']) | combine({item: {'key': item}}, recursive=True) }}"
  loop: "{{ pillar.k8s_extra_addon.keys() }}"

- name: create extra_addon
  shell: kubectl --kubeconfig={{ pillar.k8s_common.conf_dir }}/admin.conf apply -f /tmp/extra_addon_{{ item.0.key }}_{{ item.1 }}.yml
  with_subelements: 
    - "{{ pillar_k8s_extra_addon }}"
    - config_files
    - flags:
      skip_missing: True
  when: inventory_hostname in (pillar.k8s_host.master[0])
