---
- name: ensure /tmp/helm directory is create
  file:
    path: /tmp/helm
    state: directory
    mode: 0755
  when: inventory_hostname in pillar.k8s_host.master

- name: Download and unarchive helmn
  unarchive:
    src: "{{ pillar.helm_pkgs.url }}"
    dest: /tmp/helm
    remote_src: yes
  when: inventory_hostname in pillar.k8s_host.master

- name: move to bin directory
  shell: find /tmp/helm -name "helm" -type f | xargs -i /bin/mv -f {} {{ pillar.helm_pkgs.bin_dir }} && chmod 755 {{ pillar.helm_pkgs.bin_dir }}/helm
  when: inventory_hostname in pillar.k8s_host.master

- name: add helm config files
  template:
    src: helm/{{ item }}.yml.j2
    dest: /tmp/helm_{{ item }}.yml
  loop: "{{ pillar.helm_files }}"
  when: inventory_hostname in (pillar.k8s_host.master[0])

- name: apply helm config files
  shell: kubectl --kubeconfig={{ pillar.k8s_common.conf_dir }}/admin.conf apply -f /tmp/helm_{{ item }}.yml
  loop: "{{ pillar.helm_files }}"
  when: inventory_hostname in (pillar.k8s_host.master[0])

- name: init helm
  shell: helm init --wait --kubeconfig {{ pillar.k8s_common.conf_dir }}/admin.conf --service-account {{ pillar.helm_users.name }}
  when: inventory_hostname in (pillar.k8s_host.master[0])
  ignore_errors: yes
