---
- name: add helm repo
  shell: helm repo add {{ item.name }} {{ item.url }}
  when: inventory_hostname in (pillar.k8s_host.master[0])
  loop: "{{ pillar.prometheus_operator_repos }}"

- name: apply prometheus monitor from helm
  shell: helm install {{ item.repo }}/{{ item.name }} --name {{ item.name }} --namespace {{ item.namespace }}
  when: inventory_hostname in (pillar.k8s_host.master[0])
  loop: "{{ pillar.prometheus_operator_pkgs }}" 

- name: add prometheus operator config files
  template:
    src: monitor/{{ item. }}.yml.j2
    dest: /tmp/monitor_{{ item }}.yml
  loop: "{{ pillar.prometheus_operator_files }}"
  when: inventory_hostname in (pillar.k8s_host.master[0])

- name: apply prometheus operator config files
  shell: kubectl --kubeconfig={{ pillar.k8s_common.conf_dir }}/admin.conf apply -f /tmp/monitor_{{ item }}.yml
  loop: "{{ pillar.prometheus_operator_files }}"
  when: inventory_hostname in (pillar.k8s_host.master[0])
