---
- name: append key to network addon
  set_fact:
    pillar_k8s_network_addon: "{{ pillar_k8s_network_addon | default(pillar['k8s_network_addon']) | combine({item: {'key': item}}, recursive=True) }}"
  loop: "{{ pillar.k8s_network_addon.keys() }}"

- name: network addon config
  template:
    src: addon/{{ item.0.key }}/{{ item.1 }}.yml.j2
    dest: /tmp/network_addon_{{ item.0.key }}_{{ item.1 }}.yml
  with_subelements: 
    - "{{ pillar_k8s_network_addon }}"
    - config_files
  when: inventory_hostname in (pillar.k8s_host.master[0])

- name: create network addon
  shell: kubectl --kubeconfig={{ pillar.k8s_common.conf_dir }}/admin.conf apply -f /tmp/network_addon_{{ item.0.key }}_{{ item.1 }}.yml
  with_subelements: 
    - "{{ pillar_k8s_network_addon }}"
    - config_files
  when: inventory_hostname in (pillar.k8s_host.master[0])
