- name: Ensure require repos are removed.
  yum: "name={{ pillar.repo_pkgs }} state=absent"

- name: Ensure require repos are installed.
  yum: "name={{ pillar.repo_pkgs }} state=installed"

- name: Ensure require packages are installed.
  yum: "name={{ pillar.common_pkgs }} state=installed"

- name: Disable SELinux
  selinux:
    state: disabled

- name: enable service httpd and ensure it is not masked
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop: "{{ pillar.disable_srv_list }}"

# This task disables swap for Kubernetes node (see https://github.com/kubernetes/kubernetes/pull/31996)
- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: install docker
  include_tasks: docker-ce.yml

- name: Enable docker and start docker
  systemd:
    name: docker
    daemon_reload: yes
    enabled: yes

- name: adjust sysctl parameter
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_dict: "{{ pillar.sysctl }}"
