- name: Ensure require repos are removed.
  yum: "name={{ pillar.repo_pkgs }} state=absent"

- name: Ensure require repos are installed.
  yum: "name={{ pillar.repo_pkgs }} state=installed"

- name: Ensure require packages are installed.
  yum: "name={{ pillar.common_pkgs }} state=installed"

- name: Disable SELinux
  selinux:
    state: disabled

- name: enable service httpd and ensure it is not masked
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop: "{{ pillar.disable_srv_list }}"

# This task disables swap for Kubernetes node (see https://github.com/kubernetes/kubernetes/pull/31996)
- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: install docker
  include_tasks: docker-ce.yml

- name: Enable docker and start docker
  systemd:
    name: docker
    daemon_reload: yes
    enabled: yes

- name: adjust sysctl parameter
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_dict: "{{ pillar.sysctl }}"

- name: ensure cfssl bin directory is create
  file:
    path: "{{ pillar.cfssl_common.bin_dir }}"
    state: directory
    mode: 0755

- name: Download statically linked cfssl binary
  get_url:
    url: "{{ pillar.cfssl_common.url }}/{{ item.key }}"
    dest: "{{ pillar.cfssl_common.bin_dir }}/{{ item.value.dest }}"
    checksum: "{{ item.value.checksum }}"
    mode: 0755
  with_dict: "{{ pillar.cfssl_pkgs }}"

- name: ensure k8s bin directory is create
  file:
    path: "{{ pillar.k8s_common.bin_dir }}"
    state: directory
    mode: 0755

- name: Download statically linked k8s binary
  get_url:
    url: "{{ pillar.k8s_common.url }}/{{ item.key }}"
    dest: "{{ pillar.k8s_common.bin_dir }}/{{ item.value.dest }}"
    checksum: "{{ item.value.checksum }}"
    mode: 0755
  with_dict: "{{ pillar.k8s_pkgs }}"

- name: ensure cni plugin directory is create
  file:
    path: "{{ pillar.cni_common.bin_dir }}"
    state: directory
    mode: 0755

- name: Download and unarchive cni plugin
  unarchive:
    src: "{{ pillar.cni_common.url }}"
    dest: "{{ pillar.cni_common.bin_dir }}"
    remote_src: yes
