---
- name: restart docker
  systemd:
    name: docker.service
    state: restarted

- name: systemd daemon-reload
  systemd:
    daemon_reload: yes

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted
